spring.datasource.url=jdbc:postgresql://localhost:5432/tiktok_tracker
spring.datasource.username=travislin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=tiktok-tracker

rapidapi.key.shop=8cc9922d6emshb4c7249a0626321p13aa21jsnaac77a5c708e